Add `Lint/ReadInstanceVar`
crystal-ameba/ameba pull request #511
Opened 2024-11-23 11:09 UTC by nobodywasishere

Closes #463

2024-11-23 12:14 UTC, straight-shoota commented
IMHO such a rule is impossible to implement without taking scopes into account. Examples like the one in https://github.com/crystal-ameba/ameba/issues/463#issuecomment-2225517353 where an ivar is accessed from the same class should be fine.

Doing this correctly would require semantic analysis though.

2024-11-23 17:11 UTC, nobodywasishere commented
IMO in that case I think the upstream issue should be closed as no-fix.

2024-11-23 17:22 UTC, Sija commented
I think it should be doable with a low false-positive rate using a custom visitor, that ignores the access done for the object of the same class.

2024-11-23 17:32 UTC, nobodywasishere commented
Hm okay, I'll try that. Do you mean something along the lines of class/struct ClassName > def.args.any? &.restriction == ClassName or self, then reading instance vars is allow to that variable?

2024-11-23 20:24 UTC, Sija commented
Sth along these lines, yes. Top-level code as well needs to be taken into account.

2024-11-24 14:28 UTC, Sija requested changes

2024-11-24 14:28 UTC, Sija commented on src/ameba/rule/lint/read_instance_var.cr
> +  # end
Let's make the examples more abstract (like below):

```suggestion
  # class Foo
  #   def <=>(other)
  #     @ivar <=> other.@ivar
  #   end
  #
  #   def <=>(other : Bar)
  #     @ivar <=> other.@ivar
  #   end
  # end
```

2024-11-24 14:28 UTC, Sija commented on src/ameba/rule/lint/read_instance_var.cr
> +  # end
ditto

```suggestion
  # class Foo
  #   def <=>(other : self)
  #     @ivar <=> other.@ivar
  #   end
  #
  #   def <=>(other : Foo)
  #     @ivar <=> other.@ivar
  #   end
  # end
```

2024-11-24 14:28 UTC, Sija commented on src/ameba/rule/lint/read_instance_var.cr
> +  #   Enabled: false
These should list the default settings:

```suggestion
  #   Enabled: true
```

2024-11-24 14:28 UTC, Sija commented on src/ameba/rule/lint/read_instance_var.cr
> +    MSG = "Reading instance variables externally is not allowed."
Let's stick to the already established stylistic convention:

```suggestion
    MSG = "Reading instance variables externally is not allowed"
```

2024-11-24 14:28 UTC, Sija commented on src/ameba/rule/lint/read_instance_var.cr
> +    ) : Nil
```suggestion
    def test(source, node : Crystal::ReadInstanceVar, allowed_names)
```

2024-11-24 14:28 UTC, Sija commented on src/ameba/rule/lint/read_instance_var.cr
> +      @param_names : Array(String) = [] of String
Redundant type declaration

```suggestion
      @param_names = [] of String
```

2024-11-24 14:28 UTC, Sija commented on src/ameba/rule/lint/read_instance_var.cr
> +
```suggestion
```

2024-11-24 14:28 UTC, Sija commented on src/ameba/rule/lint/read_instance_var.cr
> +      end
```suggestion
      def visit(node : Crystal::ClassDef)
        prev_class = @class_name
        @class_name = node.name.names[-1]?
        begin
          node.body.accept(self)
        ensure
          @class_name = prev_class
        end
        true
      end
```

2024-11-24 14:34 UTC, Sija commented
Formatter on Crystal nightly is failing, btw.

2024-11-24 16:41 UTC, Sija commented on src/ameba/rule/lint/read_instance_var.cr
> +    def test(source, node : Crystal::ReadInstanceVar, allowed_names)
Looks like the type restriction is actually needed here, my bad.

```suggestion
    def test(source, node : Crystal::ReadInstanceVar, allowed_names : Enumerable(String))
```

2024-11-24 16:50 UTC, straight-shoota commented
As I mentioned before, it is impossible to have satisfactory type awareness without semantic analysis. 

You won't be able to determine the type of the target object with only syntactical information. The proposed implementation is very poor and limited. IIUC it only allows access to variables which are passed as parameters with explicit type restriction into a def. I'm not sure where the assumption comes from that valid access should only be allowed to parameters. It should be noted that a valid target object ought to be any kind of local variable, call, or even an instance variable read itself. But even there was justification for only considering parameters, there's still lots of issues. For example, the type of the variable at the time of the instance variable read does not need to be the same as in the method signature. Also, purely lexical comparison of paths may miss important details such as inheritance, aliases, generic arguments, ... I'm sure there are many more problems.

As a result, successful detection rate is quite miserable. IMO this is not even worth trying.
It should be better to invest the effort into figuring out how we could evolve ameba to make use of semantical information.

It's also worth noting that both human readers as well as the compiler (through semantic analysis) can easily understand the typing situation correctly. False positives on clear cases would be perceived as quite irritating issues from a linter.

2024-11-24 17:06 UTC, closed without merging

2024-11-24 17:19 UTC, Sija commented
@straight-shoota Good points, agreed.

2024-11-24 17:22 UTC, nobodywasishere commented
I agree as well. I'll create an issue to start discussion of what integrating more semantic information into ameba would look like.