Add `Typing/MethodReturnTypeRestriction`
crystal-ameba/ameba pull request #519
Opened 2024-12-02 04:19 UTC by nobodywasishere

2024-12-08 08:59 UTC, veelenga commented on spec/ameba/rule/typing/method_return_type_restriction_spec.cr
> +  subject.undocumented = true
at top level we usually test the default config, then the props can be toggled in a separate context.

2024-12-13 08:32 UTC, veelenga approved these changes
lgtm

2024-12-28 14:15 UTC, Sija requested changes

2024-12-28 14:15 UTC, Sija commented on spec/ameba/rule/typing/method_return_type_restriction_spec.cr
> +
That example seems redundant.

```suggestion
```

2024-12-28 14:15 UTC, Sija commented on spec/ameba/rule/typing/method_return_type_restriction_spec.cr
> +      end
ditto

```suggestion
```

2024-12-28 14:15 UTC, Sija commented on spec/ameba/rule/typing/method_return_type_restriction_spec.cr
> +
ditto

```suggestion
```

2024-12-28 14:15 UTC, Sija commented on spec/ameba/rule/typing/method_return_type_restriction_spec.cr
> +          end
```suggestion
```

2024-12-28 14:15 UTC, Sija commented on src/ameba/rule/typing/method_return_type_restriction.cr
> +    MSG = "Methods should have a return type restriction"
```suggestion
    MSG = "Method should have a return type restriction"
```

2024-12-28 14:15 UTC, Sija commented on src/ameba/rule/typing/method_return_type_restriction.cr
> +    def check_config(node : Crystal::ASTNode) : Bool
```suggestion
    def valid?(node : Crystal::ASTNode) : Bool
```

2024-12-28 14:15 UTC, Sija commented on src/ameba/rule/typing/method_return_type_restriction.cr
> +      undocumented false
This option doesn't seem to belong here (as in other PRs).

2024-12-28 23:29 UTC, Sija requested changes

2024-12-28 23:29 UTC, Sija commented on spec/ameba/rule/typing/method_return_type_restriction_spec.cr
> +  it "passes if a method has a return type" do
```suggestion
  it "passes if a method has a return type restriction" do
```

ditto elsewhere

2024-12-28 23:29 UTC, Sija commented on spec/ameba/rule/typing/method_return_type_restriction_spec.cr
> +      protected def hello : String
```suggestion
      protected def hello
```

2024-12-28 23:29 UTC, Sija commented on src/ameba/rule/typing/method_return_type_restriction.cr
> +  # ```
Please, keep the examples minimal, functional and list the invalid cases first.

```suggestion
  # For example, this are considered invalid:
  #
  # ```
  # def hello(name = "World")
  #   "Hello #{name}"
  # end
  # ```
  #
  # And this is valid:
  #
  # ```
  # def hello(name = "World") : String
  #   "Hello #{name}"
  # end
  # ```
```

2024-12-28 23:29 UTC, Sija commented on src/ameba/rule/typing/method_return_type_restriction.cr
> +    properties do
```suggestion
    properties do
      since_version "1.7.0"
```

2024-12-28 23:29 UTC, Sija commented on src/ameba/rule/typing/method_return_type_restriction.cr
> +      issue_for node, MSG, prefer_name_location: true
This rule relates to the whole method definition, not just the name.

```suggestion
      issue_for node, MSG
```

2024-12-29 12:57 UTC, Sija requested changes

2024-12-29 12:57 UTC, Sija commented on spec/ameba/rule/typing/method_return_type_restriction_spec.cr
> +
```suggestion
```

2024-12-29 12:57 UTC, Sija commented on src/ameba/rule/typing/method_return_type_restriction.cr
> +    end
```suggestion
    def valid_return_type?(node : Crystal::ASTNode) : Bool
      !!node.return_type ||
        (node.visibility.private? && !private_methods?) ||
          (node.visibility.protected? && !protected_methods?)
    end
```

2024-12-29 12:57 UTC, Sija commented on src/ameba/rule/typing/method_return_type_restriction.cr
> +      issue_for node, MSG
```suggestion
      issue_for node, MSG unless valid_return_type?(node)
```

2024-12-29 13:27 UTC, Sija commented on src/ameba/rule/typing/method_return_type_restriction.cr
> +          (node.visibility.protected? && !protected_methods?)
```suggestion
        (node.visibility.protected? && !protected_methods?)
```

2024-12-29 13:29 UTC, Sija approved these changes

2024-12-29 13:29 UTC, merged