Add `Style/MultiLineCurlyBlock`
crystal-ameba/ameba pull request #524
Opened 2024-12-03 02:30 UTC by nobodywasishere

Closes #523

This could have a corrector, but the different associativity between curly and `do`...`end` blocks could lead to semantic differences.

2024-12-03 07:13 UTC, Sija requested changes

2024-12-03 07:13 UTC, Sija commented on spec/ameba/rule/style/multi_line_curly_block_spec.cr
> +        incr_stack { node.accept(self) }
Please use more abstract examples:

```suggestion
        foo { :bar }
```

2024-12-03 07:13 UTC, Sija commented on spec/ameba/rule/style/multi_line_curly_block_spec.cr
> +        end
```suggestion
        foo do
          :bar
        end
```

2024-12-03 07:13 UTC, Sija commented on spec/ameba/rule/style/multi_line_curly_block_spec.cr
> +        }
```suggestion
        foo {
          # ^ error: Use `do`...`end` instead of curly brackets for multi-line blocks
          :bar
        }
```

2024-12-03 07:13 UTC, Sija commented on src/ameba/rule/style/multi_line_curly_block.cr
> +  # `do`...`end`.
```suggestion
  # A rule that disallows multi-line blocks that use curly brackets
  # instead of `do`...`end`.
```

2024-12-03 07:13 UTC, Sija commented on src/ameba/rule/style/multi_line_curly_block.cr
> +  # }
Here OTOH, examples should be closer to the _real-life_ usage:

```suggestion
  # (0..10).map { |i|
  #   i * 2
  # }
```

2024-12-03 07:13 UTC, Sija commented on src/ameba/rule/style/multi_line_curly_block.cr
> +  # end
```suggestion
  # (0..10).map do |i|
  #   i * 2
  # end
```

2024-12-03 18:05 UTC, Sija commented on spec/ameba/rule/style/multi_line_curly_block_spec.cr
> +
I'd add one more test:

```suggestion

    it "doesn't report for `do`...`end` blocks on a single line" do
      expect_no_issues subject, <<-CRYSTAL
        foo do :bar end
        CRYSTAL
    end

```

2024-12-04 05:15 UTC, Sija approved these changes

2024-12-04 05:16 UTC, Sija commented
@veelenga Squash and merge, please in case you decide to do it yourself.

2024-12-04 05:18 UTC, Sija requested changes

2024-12-04 05:18 UTC, Sija commented on src/ameba/rule/style/multi_line_curly_block.cr
> +  class MultiLineCurlyBlock < Base
One more thing:

```suggestion
  class MultilineCurlyBlock < Base
```

This incl. filenames and the rest of the places.

2024-12-04 07:53 UTC, veelenga approved these changes
lgtm

2024-12-04 07:53 UTC, merged